### ISSUE TITLE
Login no longer works

### ISSUE THREAD

**Issue by sk-** [p-roman/GarminConnectUploader#1]
It seems that Garmin changed the login endpoint and now the uploader fails to login.

**Comment by drorcohen** [comment]
I am suffering from this issue as well...

**Comment by aspiers** [comment]
Works for me so I don't think this applies any longer?

**Comment by WillForan** [comment]
previously worked for me, now:
```
Traceback (most recent call last):
  File "gupload.py", line 218, in <module>
    if not g.login(username, password):
  File "/home/foranw/src/NIH/GarminConnectUploader/UploadGarmin.py", line 121, in login
    if self._get_cookies(username=username, password=password):
  File "/home/foranw/src/NIH/GarminConnectUploader/UploadGarmin.py", line 196, in _get_cookies
    data["lt"] = re.search("name=\"lt\"\s+value=\"([^\"]+)\"", preResp.text).groups(1)[0]
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by terxw** [comment]
Same for me, I tried to uplad activities and got this error:
```

Traceback (most recent call last):
  File "/usr/local/bin/gupload.py", line 401, in <module>
    g.gupload()
  File "/usr/local/bin/gupload.py", line 238, in gupload
    if not g.login(self.username, self.password):
  File "/usr/local/lib/python2.7/dist-packages/UploadGarmin.py", line 138, in login
    if self._get_cookies(username=username, password=password):
  File "/usr/local/lib/python2.7/dist-packages/UploadGarmin.py", line 213, in _get_cookies
    data["lt"] = re.search("name=\"lt\"\s+value=\"([^\"]+)\"", preResp.text).groups(1)[0]
AttributeError: 'NoneType' object has no attribute 'groups'

```
